#define CAMERA_UP 0x01
#define CAMERA_DOWN 0x02
#define CAMERA_LEFT 0x03
#define CAMERA_RIGHT 0x04
#define FORWARD 0x05
#define LEFT 0x06
#define RIGHT 0x07
#define BACK 0x08
#define CLOSE 0x09
#define RIGHT_FORWARD 10
#define RIGHT_BACKWARD 11
#define LEFT_FORWARD 12
#define LEFT_BACKWARD 13
#define SERVO_PRESCALER 15
#define SERVO_ARR 19999
#define RIGHT_FORWARD_POSITION 0
#define RIGHT_BACKWARD_POSITION 1
#define LEFT_FORWARD_POSITION 2
#define LEFT_BACKWARD_POSITION 3

#define MOTOR_PRESCALER 0
#define MOTOR_ARR 799

#define SERVO_PWM_OUTPUT 0x00
#define MOTOR_PWM_OUTPUT 0x06
